# Generated by Django 3.2.1 on 2021-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('s_name', models.CharField(max_length=70)),
                ('s_agency_name', models.CharField(max_length=100)),
                ('s_state', models.CharField(max_length=70)),
                ('s_district', models.CharField(max_length=70)),
                ('icu_beds', models.IntegerField()),
                ('ventilator_beds', models.IntegerField()),
                ('icu_ventilator_beds', models.IntegerField()),
                ('oxygen', models.CharField(max_length=5)),
            ],
        ),
    ]
